services:
  - type: web
    name: chefboynegro-php
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_HOST
        value: dpg-xxxxxx
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: chefboynegro
      - key: DB_USER
        value: chefboyuser
      - key: DB_PASS
        value: yourpassword
